Vote Page & links to it and Dynmap in header
ComparatorCraftSMP/ComparatorCraftSMP.github.io pull request #3
Opened 2021-07-15 00:28 UTC by BraxtBooth

Created a simple vote page that we can add to or change as needed. You should add information about the "perks/rewards" of voting for the server, and possibly set background images as the possible rewards.

Dynmap link in the header just redirects to your dynmap. We could do an embedded Dynmap I'm sure but this way is super easy.

2021-07-15 00:30 UTC, BraxtBooth commented
![image](https://user-images.githubusercontent.com/50608885/125709611-baaf9018-2b81-4cd8-9aa3-cfa60b4ba28d.png)
Pic of the vote page

2021-07-18 23:21 UTC, LagunaElectric requested changes
Just a couple of changes needed.

2021-07-18 23:21 UTC, LagunaElectric commented on vote.html
> +	<title>ComparatorCraftSMP | FAQ</title>
Change "FAQ" to "Vote"

2021-07-18 23:21 UTC, LagunaElectric commented on vote.html
> +				<section id="content" }>
You left a lone `}` in your section opener.

2021-07-18 23:23 UTC, LagunaElectric approved these changes

2021-07-18 23:24 UTC, merged